/**
 * Copy a Neon database to another region, with no pg_dump on the machine.
 *
 * The DDL is not written by hand and not taken from schema.sql, which may have
 * drifted. Postgres is asked to describe its own objects — `format_type`,
 * `pg_get_constraintdef`, `pg_get_indexdef` — so what lands in the new database
 * is what is actually in the old one, including the column that really is named
 * with a leading space.
 *
 * The source is opened read-only in spirit: this script never writes to it.
 *
 *   node scripts/migrate-region.cjs           # copy (destination must be empty)
 *   node scripts/migrate-region.cjs --fresh   # empty the destination first, then copy
 *   node scripts/migrate-region.cjs --verify  # compare the two, change nothing
 */
const { Pool } = require("pg");
require("dotenv").config({ path: require("path").join(__dirname, "..", ".env") });

const VERIFY_ONLY = process.argv.includes("--verify");
const FRESH = process.argv.includes("--fresh");
const SRC = process.env.DATABASE_URL;
const DST = process.env.NEW_DB_URL;
if (!SRC || !DST) { console.error("Need DATABASE_URL and NEW_DB_URL"); process.exit(1); }

const src = new Pool({ connectionString: SRC, ssl: { rejectUnauthorized: false }, max: 4 });
const dst = new Pool({ connectionString: DST, ssl: { rejectUnauthorized: false }, max: 4 });

const q = (pool, text, params) => pool.query(text, params).then((r) => r.rows);
const ident = (name) => '"' + String(name).replace(/"/g, '""') + '"';

async function tableList(pool) {
  return (await q(pool, `
    SELECT c.relname AS name
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind = 'r'
    ORDER BY c.relname`)).map((r) => r.name);
}

async function buildSchema() {
  console.log("\n── Reading the source schema ──");

  const seqs = await q(src, `
    SELECT c.relname AS name
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname='public' AND c.relkind='S' ORDER BY 1`);
  console.log(`   sequences: ${seqs.length}`);

  const tables = await tableList(src);
  console.log(`   tables:    ${tables.length}`);

  // Columns, straight from the catalog so types come back exactly as stored.
  const cols = await q(src, `
    SELECT c.relname AS tbl, a.attname AS col, a.attnum,
           format_type(a.atttypid, a.atttypmod) AS type,
           a.attnotnull AS notnull,
           pg_get_expr(d.adbin, d.adrelid) AS default_expr,
           a.attidentity AS identity
    FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
    WHERE n.nspname='public' AND c.relkind='r' AND a.attnum > 0 AND NOT a.attisdropped
    ORDER BY c.relname, a.attnum`);

  // Constraints: primary/unique/check first, foreign keys afterwards so the
  // tables they point at already exist.
  const cons = await q(src, `
    SELECT c.relname AS tbl, con.conname AS name, con.contype AS type,
           pg_get_constraintdef(con.oid) AS def
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname='public'
    ORDER BY CASE con.contype WHEN 'p' THEN 1 WHEN 'u' THEN 2 WHEN 'c' THEN 3 ELSE 4 END,
             c.relname, con.conname`);

  // Indexes that are not already implied by a constraint.
  const idx = await q(src, `
    SELECT i.indexname AS name, i.indexdef AS def
    FROM pg_indexes i
    WHERE i.schemaname='public'
      AND NOT EXISTS (
        SELECT 1 FROM pg_constraint con
        WHERE con.conname = i.indexname
          AND con.connamespace = 'public'::regnamespace)
    ORDER BY i.indexname`);

  console.log(`   columns:   ${cols.length}`);
  console.log(`   constraints: ${cons.length}  (fk: ${cons.filter(c => c.type === 'f').length})`);
  console.log(`   extra indexes: ${idx.length}`);

  return { seqs, tables, cols, cons, idx };
}

async function createSchema({ seqs, tables, cols, cons, idx }) {
  console.log("\n── Creating it on the destination ──");

  for (const s of seqs) {
    await dst.query(`CREATE SEQUENCE IF NOT EXISTS ${ident(s.name)}`);
  }
  console.log(`   ${seqs.length} sequences`);

  for (const t of tables) {
    const mine = cols.filter((c) => c.tbl === t);
    const defs = mine.map((c) => {
      let line = `${ident(c.col)} ${c.type}`;
      if (c.identity === "a") line += " GENERATED ALWAYS AS IDENTITY";
      else if (c.identity === "d") line += " GENERATED BY DEFAULT AS IDENTITY";
      else if (c.default_expr) line += ` DEFAULT ${c.default_expr}`;
      if (c.notnull) line += " NOT NULL";
      return "  " + line;
    });
    await dst.query(`CREATE TABLE IF NOT EXISTS ${ident(t)} (\n${defs.join(",\n")}\n)`);
  }
  console.log(`   ${tables.length} tables`);

  return { cons, idx };
}

async function copyData(tables) {
  console.log("\n── Copying rows ──");

  // Get column types so we can cast json/jsonb values to string before insert.
  const colTypes = await q(src, `
    SELECT c.relname AS tbl, a.attname AS col,
           format_type(a.atttypid, a.atttypmod) AS type
    FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname='public' AND c.relkind='r' AND a.attnum > 0 AND NOT a.attisdropped`);
  const typeMap = {};
  for (const r of colTypes) {
    if (!typeMap[r.tbl]) typeMap[r.tbl] = {};
    typeMap[r.tbl][r.col] = r.type;
  }

  const isJsonType = (t) => t === "json" || t === "jsonb";

  let grand = 0;
  for (const t of tables) {
    const [{ n }] = await q(src, `SELECT COUNT(*)::int n FROM ${ident(t)}`);
    if (n === 0) { console.log(`   ${t.padEnd(22)} empty`); continue; }

    const rows = await q(src, `SELECT * FROM ${ident(t)}`);
    const keys = Object.keys(rows[0]);
    const colList = keys.map(ident).join(", ");
    const tblTypes = typeMap[t] || {};

    // Batched so a wide table does not build one enormous statement.
    const BATCH = 200;
    for (let i = 0; i < rows.length; i += BATCH) {
      const slice = rows.slice(i, i + BATCH);
      const params = [];
      const tuples = slice.map((row) => {
        const marks = keys.map((k) => {
          let val = row[k];
          // Serialize json/jsonb columns to string so pg driver doesn't choke.
          if (val !== null && val !== undefined && isJsonType(tblTypes[k])) {
            if (typeof val !== "string") val = JSON.stringify(val);
          }
          params.push(val);
          return `$${params.length}`;
        });
        return `(${marks.join(",")})`;
      });
      await dst.query(
        `INSERT INTO ${ident(t)} (${colList}) VALUES ${tuples.join(",")} ON CONFLICT DO NOTHING`,
        params);
    }
    grand += n;
    console.log(`   ${t.padEnd(22)} ${n}`);
  }
  console.log(`   ${grand} rows in total`);
}

async function applyConstraints({ cons, idx }, phase) {
  // Primary and unique keys must exist BEFORE the rows arrive. They are what
  // gives ON CONFLICT DO NOTHING anything to conflict against, and therefore
  // what makes running this script a second time harmless. Applying them
  // afterwards — as the first version did — meant a re-run silently tripled
  // every table, and then the keys could no longer be created at all.
  const wanted = phase === "keys"
    ? cons.filter((c) => c.type === "p" || c.type === "u")
    : cons.filter((c) => c.type !== "p" && c.type !== "u");

  console.log(`\n── Constraints: ${phase === "keys" ? "keys, before the data" : "checks, foreign keys, indexes"} ──`);
  let ok = 0, skipped = [];
  for (const c of wanted) {
    try {
      await dst.query(`ALTER TABLE ${ident(c.tbl)} ADD CONSTRAINT ${ident(c.name)} ${c.def}`);
      ok++;
    } catch (e) {
      if (/already exists/.test(e.message)) ok++;
      else skipped.push(`${c.tbl}.${c.name}: ${e.message}`);
    }
  }
  console.log(`   ${ok} constraints applied`);
  if (skipped.length) skipped.forEach((s) => console.log(`   SKIPPED ${s}`));
  if (phase === "keys") return skipped.length;

  let iok = 0, iskip = [];
  for (const i of idx) {
    try { await dst.query(i.def); iok++; }
    catch (e) {
      if (/already exists/.test(e.message)) iok++;
      else iskip.push(`${i.name}: ${e.message}`);
    }
  }
  console.log(`   ${iok} indexes applied`);
  if (iskip.length) iskip.forEach((s) => console.log(`   SKIPPED ${s}`));
  return skipped.length + iskip.length;
}

async function fixSequences() {
  console.log("\n── Sequence positions ──");
  // Every sequence that backs a column is moved past the largest value already
  // in it, or the next insert collides with a row that was just copied.
  const owned = await q(src, `
    SELECT s.relname AS seq, c.relname AS tbl, a.attname AS col
    FROM pg_class s
    JOIN pg_depend d ON d.objid = s.oid AND d.classid = 'pg_class'::regclass
    JOIN pg_class c ON c.oid = d.refobjid
    JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = d.refobjsubid
    JOIN pg_namespace n ON n.oid = s.relnamespace
    WHERE s.relkind = 'S' AND n.nspname = 'public'`);

  // Re-establish ownership. The sequences are created standalone and the tables
  // reference them through a DEFAULT, which works — but without OWNED BY the
  // catalog has no link between the two, so pg_depend lookups (including the
  // one below) find nothing and a dropped table would leave its sequence behind.
  for (const o of owned) {
    try {
      await dst.query(
        `ALTER SEQUENCE ${ident(o.seq)} OWNED BY ${ident(o.tbl)}.${ident(o.col)}`);
    } catch (e) {
      console.log(`   SKIPPED ownership for ${o.seq}: ${e.message}`);
    }
  }

  let repoCount = 0;
  for (const o of owned) {
    let mx;
    try {
      [{ mx }] = await q(dst, `SELECT COALESCE(MAX(${ident(o.col)}), 0) AS mx FROM ${ident(o.tbl)}`);
    } catch (e) {
      console.log(`   SKIPPED seq reposition for ${o.seq}: ${e.message}`);
      continue;
    }
    try {
      // quote_ident matters: a bare string cast to regclass is folded to lower
      // case, so "ORDER_or_id_seq" was looked up as "order_or_id_seq" and 30 of
      // 35 sequences silently stayed at 1 — which would have collided with an
      // existing row on the very first sale after cutover.
      await dst.query(`SELECT setval(quote_ident($1)::regclass, $2, true)`,
        [o.seq, Number(mx) > 0 ? Number(mx) : 1]);
      repoCount++;
    } catch (e) {
      console.log(`   SKIPPED setval for ${o.seq}: ${e.message}`);
    }
  }
  console.log(`   ${repoCount}/${owned.length} sequences repositioned`);
}

/**
 * Never top up a destination that already holds rows.
 *
 * Copying into a half-finished database is exactly how every table ended up
 * tripled. Either it is empty, or the caller says --fresh and means it.
 */
async function refuseIfNotEmpty() {
  const tables = await tableList(dst);
  if (!tables.length) return;
  let rows = 0;
  for (const t of tables) {
    try { rows += (await q(dst, `SELECT COUNT(*)::int n FROM ${ident(t)}`))[0].n; } catch {}
  }
  if (rows > 0) {
    throw new Error(
      `the destination already holds ${rows} rows across ${tables.length} tables.\n` +
      `        Copying again would duplicate them. To start it over cleanly:\n` +
      `          node scripts/migrate-region.cjs --fresh`);
  }
}

/** Empty the destination. Guarded so it can never be aimed at the source. */
async function wipeDestination() {
  if (!DST || DST === SRC) throw new Error("refusing to wipe: destination is the source");
  const [{ d }] = await q(dst, "SELECT current_database() d, current_user");
  console.log(`\n── Emptying the destination (${d}) ──`);
  await dst.query("DROP SCHEMA public CASCADE");
  await dst.query("CREATE SCHEMA public");
  console.log("   done; the source was not touched");
}

async function verify() {
  console.log("\n── Verifying ──");
  const tables = await tableList(src);
  const dstTables = await tableList(dst);

  const missing = tables.filter((t) => !dstTables.includes(t));
  if (missing.length) console.log(`   MISSING TABLES: ${missing.join(", ")}`);

  let bad = 0, total = 0;
  for (const t of tables) {
    const [{ n: a }] = await q(src, `SELECT COUNT(*)::int n FROM ${ident(t)}`);
    let b = -1;
    try { [{ n: b }] = await q(dst, `SELECT COUNT(*)::int n FROM ${ident(t)}`); } catch {}
    total += a;
    if (a !== b) { console.log(`   MISMATCH ${t.padEnd(22)} source ${a}  destination ${b}`); bad++; }
  }
  console.log(`   ${tables.length - bad}/${tables.length} tables match  (${total} source rows)`);

  const [{ n: sc }] = await q(src,
    `SELECT COUNT(*)::int n FROM pg_constraint WHERE connamespace='public'::regnamespace`);
  const [{ n: dc }] = await q(dst,
    `SELECT COUNT(*)::int n FROM pg_constraint WHERE connamespace='public'::regnamespace`);
  console.log(`   constraints: source ${sc}, destination ${dc}${sc === dc ? "" : "  <-- DIFFERENT"}`);

  return { bad, missing: missing.length, constraintGap: sc - dc };
}

(async () => {
  try {
    if (VERIFY_ONLY) { await verify(); return; }

    const schema = await buildSchema();

    if (FRESH) await wipeDestination();
    else await refuseIfNotEmpty();

    await createSchema(schema);
    await applyConstraints(schema, "keys");   // keys first, so a re-run is safe
    await copyData(schema.tables);
    await applyConstraints(schema, "rest");
    await fixSequences();
    const r = await verify();
    console.log(r.bad === 0 && r.missing === 0
      ? "\nDONE — the copy matches the source."
      : "\nDONE WITH DIFFERENCES — see above before switching anything over.");
  } catch (e) {
    console.error("\nFAILED: " + e.message);
    process.exitCode = 1;
  } finally {
    await src.end().catch(() => {});
    await dst.end().catch(() => {});
  }
})();
